services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/workspace
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY="THE API KEY"
      - POSTGRES_URL=

  db:
    image: postgres:13.2-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=madatabase
      - POSTGRES_USER=mauser
      - POSTGRES_PASSWORD=mapassword
    ports:
      - "5432:5432"

  ui:
    build: ./ui
    ports:
      - "5173:80"
