variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build_backend:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info    
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd backend
    - docker build -t yjack0000cs12/medicopilot-backend:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID .
    - docker push yjack0000cs12/medicopilot-backend:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
  only:
    - dev
    - main

build_frontend:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info  
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd ui
    - docker build -t yjack0000cs12/medicopilot-ui:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID .
    - docker push yjack0000cs12/medicopilot-ui:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
  only:
    - dev
    - main
