build_backend:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info    
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd backend
    - docker build -t yjack0000cs12/medicopilot-backend:$CI_COMMIT_REF_SLUG .
    - docker push yjack0000cs12/medicopilot-frontend:$CI_COMMIT_REF_SLUG
  only:
    - dev
    - main

build_frontend:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info  
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd frontend
    - docker build -t yjack0000cs12/medicopilot-frontend:$CI_COMMIT_REF_SLUG .
    - docker push yjack0000cs12/medicopilot-frontend:$CI_COMMIT_REF_SLUG
  only:
    - dev
    - main
