unit-test-job:  
  stage: lint-and-test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "Test good good because you are good."

lint-test-job:
  stage: lint-and-test
  script:
    - echo "Linting code... "
    - echo "No lint issues found. You write nothin about linting. "

