name: Deploy to Firebase Hosting

on:
  push:
    # branches:
    #   - main # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: echo ${{ secrets.FIREBASE_API_KEY_LINE }} > .env &&\
            echo "VITE_FIREBASE_AUTH_DOMAIN=mediguess-assistant.firebaseapp.com" >> .env &&\
            echo "VITE_FIREBASE_PROJECT_ID=mediguess-assistant" >> .env &&\
            echo ${{ secret.FIREBASE_MESSAGING_SENDER_ID_LINE }} >> .env &&\
            echo ${{ secret.FIREBASE_APP_ID_LINE }} >> .env &&\
            echo ${{ secret.FIREBASE_MEASUREMENT_ID_LINE }} >> .env
      
      - name: Build
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main'
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
